---

- name: add group ogn
  group: 
    name: ogn

- name: add user ogn
  user: 
    name: ogn 
    group: ogn 
 
- name: install required packages
  package: 
    name: "{{ item }}" 
  with_items:
  - rtl-sdr
  - libconfig-dev
  - fftw3-dev
  - libjpeg-dev
  - libjpeg8
  - libconfig9

- name: download rtlsdr ogn binary
  get_url: 
    url: "{{ rtlsdr_ogn_bin_url }}" 
    dest: "/opt/{{ rtlsdr_ogn_bin }}"
  register: ogn_download
  tags: updateogn

- name: delete old directory
  file: 
    path: "/opt/{{ item }}" 
    state: absent
  when: ogn_download.changed
  with_items:
    - rtlsdr-ogn
  tags: updateogn

- name: ...and extract it
  unarchive: 
    src: "/opt/{{ rtlsdr_ogn_bin }}" 
    dest: "/opt/" 
    creates: "/opt/{{ rtlsdr_ogn_dir }}" 
    copy: no 
    owner: root 
    group: root
  tags: updateogn

- name: symlink directory
  file: 
    src: "/opt/{{ rtlsdr_ogn_dir }}" 
    path: "/opt/rtlsdr-ogn" 
    state: link 
    owner: root 
    group: root
  tags: updateogn

- name: change ownership recursive
  file: 
    path: "/opt/rtlsdr-ogn/"
    state: directory 
    owner: root 
    group: root 
    recurse: yes
  tags: updateogn

- name: create ogn config directory
  file: 
    path: "/etc/rtlsdr-ogn" 
    state: directory 
    owner: root 
    group: root

- name: create ogn site config file
  template: 
    src: "site.conf.j2" 
    dest: "/etc/rtlsdr-ogn/site.conf"
  tags:
    - updatesiteconf

- name: create ogn systemd service unit files
  copy: 
    src: "{{ item }}" 
    dest: "/etc/systemd/system/{{ item }}" 
    owner: root 
    group: root 
    mode: 0644
  with_items: "{{ ogn_services }}"
  register: "install_config"
  tags: start

- name: notify systemd of config changes
  systemd: 
    name: "{{ item.item }}"  
    daemon_reload: yes
    enabled: true
    state: restarted
  with_items: "{{ install_config.results }}"
  when: "{{ item.changed == true }}" 
  tags: start

- name: enable and start services 
  service: 
    name: "{{ item }}"
    enabled: yes 
    state: started
  with_items: "{{ ogn_services }}"
  tags: start
